feat: schema change
jambonz/jambonz-api-server pull request #169
Opened 2023-05-12 05:52 UTC by xquanluu

2023-05-31 18:56 UTC, davehorton commented
I get this warning when testing
```
3|jambonz-api-server      | (node:30196) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
3|jambonz-api-server      | Please migrate your code to use AWS SDK for JavaScript (v3).
3|jambonz-api-server      | For more information, check the migration guide at https://a.co/7PzMCcy
3|jambonz-api-server      | (Use `node --trace-warnings ...` to show where the warning was created)
3|jambonz-api-server      | {"level":30, "time": "2023-05-31T18:24:27.924Z","pid":30196,"hostname":"ip-10-0-53-191","obj":{"sampleRate":8000,"mixType":"stereo","ca
```

We should update to AWS SDK v3

2023-06-02 03:39 UTC, xquanluu commented
Hi @avoylenko 
The first working commit was using wav file, then we identified that the wav file was too big size, 1 min 30 seconds duration call could cost ~ 4MB file. after that we chose mp3 for this feature.

Hi @davehorton 
should we have new drop down list  in bucket credential for choosing which type of audio(wav/mp3) should be stored?

2023-06-02 11:38 UTC, davehorton commented
yes, let's offer configuration - wav vs mp3

2023-06-04 12:05 UTC, davehorton approved these changes

2023-06-04 12:06 UTC, davehorton approved these changes

2023-06-04 12:06 UTC, davehorton approved these changes

2023-06-04 12:07 UTC, davehorton requested changes

2023-06-04 12:07 UTC, davehorton commented on db/upgrade-jambonz-db.js
> +  8004: [
please add the record_format alter table statement here so when we upgrade existing databases it is created

2023-06-04 16:00 UTC, davehorton requested changes

2023-06-04 16:00 UTC, davehorton commented on lib/record/s3.js
> +        const {sampleRate, accountSid, callSid} = obj;
In addition to these properties, I would also like to create metadata properties in the S3 uploaded file for:
- direction
- from
- to 
- callId
- applicationSid
- originatingSipIp
- originatingSipTrunkName

2023-06-05 17:10 UTC, davehorton requested changes

2023-06-05 17:10 UTC, davehorton commented on db/upgrade-jambonz-db.js
> +  8004: [
@xquanluu this is still needed

2023-06-05 17:12 UTC, davehorton requested changes

2023-06-05 17:12 UTC, davehorton commented on db/jambones-sql.sql
> +record_format VARCHAR(16) NOT NULL DEFAULT 'mp3',
this needs to be added to the upgrade db script

2023-06-09 15:15 UTC, davehorton requested changes

2023-06-09 15:15 UTC, davehorton commented on lib/routes/api/accounts.js
> +            name = o.name;
region is discarded if passed along, as a result this only works for us-east-1

2023-06-09 18:56 UTC, davehorton approved these changes

2023-06-09 18:57 UTC, merged